# Generated by Django 6.0.2 on 2026-02-27 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Lpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'ЛПУ',
                'verbose_name_plural': 'ЛПУ',
            },
        ),
        migrations.CreateModel(
            name='LpuInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('has_parking', models.BooleanField(db_default=False, verbose_name='Есть парковка')),
                ('has_pandus', models.BooleanField(db_default=False, verbose_name='Есть пандус')),
                ('lpu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctors.lpu', verbose_name='ЛПУ')),
            ],
            options={
                'verbose_name': 'Информация о ЛПУ',
                'verbose_name_plural': 'Информации о ЛПУ',
            },
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('online_appointment_on', models.BooleanField(db_default=False, verbose_name='Включена онлайн-запись')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Врач')),
                ('lpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.lpu', verbose_name='ЛПУ')),
            ],
            options={
                'verbose_name': 'Место работы врача',
                'verbose_name_plural': 'Места работы врачей',
            },
        ),
    ]
