# Generated by Django 6.0.2 on 2026-02-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LpuSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сеть ЛПУ',
                'verbose_name_plural': 'Сети ЛПУ',
            },
        ),
    ]
