# Generated by Django 6.0.2 on 2026-02-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_lpuset'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpu',
            name='lpu_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.lpuset', verbose_name='Сеть ЛПУ'),
        ),
    ]
