# Generated by Django 6.0.2 on 2026-02-28 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('price', models.PositiveIntegerField(verbose_name='Цена услуги')),
                ('lpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.lpu', verbose_name='ЛПУ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга в ЛПУ',
                'verbose_name_plural': 'Услуги в ЛПУ',
            },
        ),
    ]
