# Generated by Django 6.0.2 on 2026-02-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_serviceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpu',
            name='services',
            field=models.ManyToManyField(through='doctors.ServicePrice', to='doctors.service', verbose_name='Услуги'),
        ),
    ]
