# Generated by Django 6.0.2 on 2026-03-08 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_lpu_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.workplace', verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
            },
        ),
    ]
