# Generated by Django 6.0.2 on 2026-03-19 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Мастер врача'),
        ),
    ]
