# Generated by Django 6.0.2 on 2026-03-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctor_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManipulationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(unique=True, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип манипуляции',
                'verbose_name_plural': 'Типы манипуляции',
            },
        ),
        migrations.CreateModel(
            name='Manipulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Доктор')),
                ('mtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.manipulationtype', verbose_name='Тип манипуляции')),
            ],
            options={
                'verbose_name': 'Манипуляция врача',
                'verbose_name_plural': 'Манипуляции врачей',
            },
        ),
        migrations.CreateModel(
            name='MKBType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('code', models.CharField(unique=True, verbose_name='Код болезни')),
                ('manipulation_types', models.ManyToManyField(to='doctors.manipulationtype')),
            ],
            options={
                'verbose_name': 'Болезнь по МКБ-10',
                'verbose_name_plural': 'Болезни по МКБ-10',
            },
        ),
        migrations.CreateModel(
            name='DoctorMKBTypePractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Доктор')),
                ('mkb_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.mkbtype', verbose_name='МКБ-болезнь')),
            ],
            options={
                'verbose_name': 'Практика врача по МКБ',
                'verbose_name_plural': 'Практики врача по МКБ',
            },
        ),
    ]
