# Generated by Django 6.0.2 on 2026-03-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_manipulationtype_manipulation_mkbtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manipulation',
            name='is_parsed',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Автоматическая запись'),
        ),
    ]
