# Generated by Django 6.0.2 on 2026-03-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_manipulation_is_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='manipulation',
            name='frequency',
            field=models.IntegerField(null=True),
        ),
    ]
