# Generated by Django 6.0.2 on 2026-03-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_manipulation_frequency'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manipulation',
            constraint=models.UniqueConstraint(fields=('doctor', 'mtype'), name='unique_doctor_mtype'),
        ),
    ]
