# Generated by Django 6.0.2 on 2026-03-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_manipulation_unique_doctor_mtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('total_appointments', models.PositiveIntegerField(verbose_name='Общее число приёмов')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Практика врача',
                'verbose_name_plural': 'Практики врачей',
            },
        ),
    ]
