# Generated by Django 6.0.2 on 2026-03-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_doctorpractice'),
    ]

    operations = [
        migrations.AddField(
            model_name='manipulation',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True, verbose_name='Активность записи'),
        ),
    ]
