# Generated by Django 6.0.2 on 2026-03-25 18:26

import django.core.validators
import django.db.models.deletion
import doctors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_manipulation_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('processed_image', models.ImageField(blank=True, default='', max_length=200, upload_to=doctors.models.get_service_appointment_direction_filepath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpeg', 'jpg', 'png', 'heic', 'pdf'))], verbose_name='Обработанное изображение направления')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.appointment', verbose_name='Запись к врачу')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
