# Generated by Django 6.0.2 on 2026-03-31 18:59

import django.core.validators
import doctors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_appointmentdirection'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormkbtypepractice',
            name='total_appointments',
            field=models.PositiveIntegerField(db_default=0, default=0, verbose_name='Число приёмов'),
        ),
        migrations.AlterField(
            model_name='appointmentdirection',
            name='processed_image',
            field=models.ImageField(blank=True, default='', max_length=200, upload_to=doctors.models.get_service_appointment_direction_filepath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpeg', 'jpg', 'png', 'heic'))], verbose_name='Обработанное изображение направления'),
        ),
    ]
